FROM nginx
COPY conf/ /etc/nginx/conf.d/
WORKDIR /etc/nginx/conf.d/
# ssl 생성
#https://zetawiki.com/wiki/%EB%A6%AC%EB%88%85%EC%8A%A4_%EC%9E%90%EC%B2%B4%EC%84%9C%EB%AA%85_SSL_%EC%9D%B8%EC%A6%9D%EC%84%9C_%EC%83%9D%EC%84%B1#